channels/r_asiangirlsbeingcute/app.py
this as per requested before for @asiangirlsbeingcute channel on telegram
=> added for asiangirlsbeingcute channels

channels/r_asiangirlsbeingcute/app.py
modify get_url function to get_gif, for retrieve 2mb gif from gfycat.com
=> modify get url for gfycat as get_gif

channels/r_unexpected/__init__.py, channels/r_unexpected/app.py, requirements.txt
Using the new url upload mode, where telegram servers are handling the file download.
Needs [pytgbot](https://github.com/luckydonald/pytgbot/) for that, telepot can't do that yet. 
```sh
pip install pytgbot
```
Disclaimer: I developed that Library.
=> Added /r/Unexpected.

channels/r_unexpected/app.py, requirements.txt
Resolves the errors of **r_unexpected** in https://github.com/Fillll/reddit2telegram/pull/9
=> Updated pytgbot and removed duplicate code.

.gitignore, Dockerfile, README.md, docker-compose.yml, imgur.yml.example, main_app.py, prod.yml.example
=> Docker support & configuration examples

channels/r_unexpected/app.py, main_app.py, requirements.txt, sentry.py
- Now trying different ways to get the gif.
- Not creating a bot for each iteration.
- Updated pytgbot requirement
- Allow bot to work, if no sentry is configured.
=> Several Improvements

README.md
=> /r/mylittlepony

channels/r_unexpected/app.py
Because they went retarded, and are forcing german-only postings on /r/Unexpected.
=> Translate it to english

channels/dailyfoodporn/__init__.py, channels/dailyfoodporn/app.py
just added new dailyfoodporn channel
=> add dailyfoodporn channel

channels/r_overwatch/__init__.py, channels/r_overwatch/app.py
Attempt to add bot to post gifs from r/overwatch :)
=> Adding r_overwatch

channels/r_listentothis/app.py
=> Typo in the channel name D:

channels/r_pantsu/__init__.py, channels/r_pantsu/app.py
Nothing special. Probably worth a test run.
=> Add r_pantsu - two line edit from awwnime

channels/freefolk/__init__.py, channels/freefolk/app.py
Adding channel for https://www.reddit.com/r/freefolk/ subreddit.
=> add r/freefolk

README.md, channels/r_slimerancher/__init__.py, channels/r_slimerancher/app.py
I just wanted to add r/slimerancher. 
I'd like all the posts to be sent to the tg channel. Don't know if I did it correctly tho.
=> Adding r/slimerancher

channels/r_slimerancher/app.py
Just look through changes if the syntax is correct
=> Fix to r_slimerancher

channels/r_rupaulsdragrace/__init__.py, channels/r_rupaulsdragrace/app.py
Please add this subreddit to the bot, I hope I've done everything correctly
=> Added support for /r/rupaulsdragrace subreddit

channels/GIFFFs
I'm not sure I made it right, the file I mean. Hope it's ok.
=> GIFFFs channel

channels/r_BigAnimeTiddies/__init__.py, channels/r_BigAnimeTiddies/app.py, channels/r_Damnthatsinteresting/__init__.py, channels/r_Damnthatsinteresting/app.py
Please Create the Channels for Them on Telegram as Well.
I tried but the bot could not be added into them, much less set as admin.
Thank You.
=> Add Damnthatsinteresting Sub & Others

channels/fakealbumcovers/__init__.py, channels/fakealbumcovers/app.py
Added code for r/fakealbumcovers
=> Add r/fakealbumcovers

utils.py
Doesn't change the functions to other channels
=> Added parse_mode to Images and Gifs (API 3.6)

channels/fakealbumcovers/app.py
Added new separator
Removed "[Request]"s posts
=> Fixes for FakeAlbumCovers

README.md, channels/r_techsupportgore/__init__.py, channels/r_techsupportgore/app.py
I guess I've done everything correctly. 
I would add more channels but I hit the tg public channel limit :/ I need another tg account.
=> Add TechSupportGore channel

channels/r_chemicalreactionsgifs/__init__.py, channels/r_chemicalreactionsgifs/app.py
Adding support for [chemicalreactiongifs](https://www.reddit.com/r/chemicalreactiongifs/)
=> Adding support for chemicalreactiongifs

channels/r_wheredidthesodago/__init__.py, channels/r_wheredidthesodago/app.py
Adding support for [wheredidthesodago](https://www.reddit.com/r/wheredidthesodago/)
=> Adding support for wheredidthesodago

channels/wasletztepreis/app.py
Due to technical difficulties the bot isn't added to the channel yet but this will be done asap.
=> Add Support for /r/wasletztepreis

greentext/app.py
Same Problem as my last commitment. I can't add the bot to the channel (yet).
=> Add Support for /r/greentext

channels/fakealbumcovers/app.py
Added filters for self titled albums, requests. Also new separators.
=> Enhanced FakeAlbumCovers

channels/r_disneyvacation/__init__.py, channels/r_disneyvacation/app.py, own.cron
cron is set on each hour 15 mins, change it if you need to
=> Added r/disneyvacation

channels/r_indonesia/__init__.py, channels/r_indonesia/app.py
Adding r_indonesia to the loop
=> Add r_indonesia

channels/r_latestagecapitalism/__init__.py, channels/r_latestagecapitalism/app.py
Adding /r/latestagecapitalism to channels
=> Add r_latestagecapitalism

channels/ShitLiberalsSay/__init__.py, channels/ShitLiberalsSay/app.py
Adding /r/ShitLiberalsSay to channels
=> Add ShitLiberalsSay

channels/r_ContraPoints/__init__.py, channels/r_ContraPoints/app.py
Adding /r/ContraPoints to channels
=> Add r_ContraPoints

README.md, channels/ingress/__init__.py, channels/ingress/app.py, own.cron
/r/Ingress
https://t.me/IngressReddit
https://t.me/IngressReddit
=> Add Ingress Reddit Channel to the Bot

reddit2telegram/channels/r_latestagecapitalism/tags.txt
tags.txt in r_latestagecapitalism updated
=> tags update

reddit2telegram/channels/r_breadtube/__init__.py, reddit2telegram/channels/r_breadtube/app.py, reddit2telegram/channels/r_breadtube/tags.txt
=> Add /r/breadtube

reddit2telegram/channels/r_grandorder/app.py
r/FGOmemes/
https://t.me/r_grandorder
=> Add r/FGOmemes/ to r_grandorder/app.py

reddit2telegram/channels/r_grandorder/app.py
=> Remove FGOMemes from @r_grandorder

reddit2telegram/channels/r_invites/app.py
=> @r_invites

README.md, reddit2telegram/channels/r_rust/__init__.py, reddit2telegram/channels/r_rust/app.py, reddit2telegram/own.cron
[/r/rust](https://www.reddit.com/r/rust/)
[@r_rust](https://t.me/r_rust)
=> added rust subreddit

reddit2telegram/channels/r_lua/TAGS.txt, reddit2telegram/channels/r_lua/__init__.py, reddit2telegram/channels/r_lua/app.py
Telegram channel: https://t.me/r_lua
=> Lua - Reddit

README.md, reddit2telegram/channels/r_comedyheaven/__init__.py, reddit2telegram/channels/r_comedyheaven/app.py, reddit2telegram/channels/r_comedyheaven/tags.txt, reddit2telegram/own.cron
_[/r/comedyheaven](https://reddit.com/r/comedyheaven)_
_[@r_comedyheaven](https://t.me/r_comedyheaven)_
I have not updated `own.cron` because I'm not sure how it works.
=> Add /r/comedyheaven

reddit2telegram/channels/r_notinteresting/__init__.py, reddit2telegram/channels/r_notinteresting/app.py, reddit2telegram/channels/r_notinteresting/tags.txt, reddit2telegram/own.cron
[/r/notinteresting](https://www.reddit.com/r/notinteresting/)
[\@r_notinteresting](https://t.me/r_notinteresting)
=> Add the subreddit /r/notinteresting

reddit2telegram/channels/r_zig/TAGS.txt, reddit2telegram/channels/r_zig/__init__.py, reddit2telegram/channels/r_zig/app.py
https://www.reddit.com/r/Zig
https://t.me/r_zig
=> ZigLang - Reddit

reddit2telegram/channels/r_shitpostxiv/__init__.py, reddit2telegram/channels/r_shitpostxiv/app.py, reddit2telegram/own.cron
https://www.reddit.com/r/ShitpostXIV/
https://t.me/r_ShitpostXIV
=> Added ShitpostXIV

reddit2telegram/channels/r_unexpectedhamilton/__init__.py, reddit2telegram/channels/r_unexpectedhamilton/app.py, reddit2telegram/channels/r_unexpectedhamilton/tags.txt, reddit2telegram/own.cron
[/r/UnexpectedHamilton](https://reddit.com/r/UnexpectedHamilton)
[@r_unexpectedhamilton](https://t.me/r_unexpectedhamilton)
I chose to update it only twice each day (rather than 24 times) because the post frequency is pretty low. If it is more appropriate to have the bot check every hour, that's totally fine and I can update the PR.
=> Add the subreddit /r/UnexpectedHamilton

reddit2telegram/channels/r_lal_salaam/app.py, reddit2telegram/channels/r_lal_salaam/tags.txt
https://www.reddit.com/r/Lal_Salaam/
https://t.me/r_Lal_Salaam
=> Added r/Lal_Salaam

reddit2telegram/channels/r_theofficememes/__init__.py, reddit2telegram/channels/r_theofficememes/app.py, reddit2telegram/channels/r_theofficememes/tags.txt, reddit2telegram/own.cron
https://www.reddit.com/r/theofficememes/
https://t.me/r_theofficememes
=> Added r_theofficememes

reddit2telegram/channels/r_denmark/app.py, reddit2telegram/channels/r_denmark/tags.txt
[/r/denmark](https://www.reddit.com/r/Denmark)
[@r_denmark](https://t.me/r_denmark)
=> Add r_denmark

reddit2telegram/channels/tnomod/_init_.py, reddit2telegram/channels/tnomod/app.py, reddit2telegram/channels/tnomod/tags.txt, reddit2telegram/own.cron
r/TNOmod and r/dsrfunny
@TNOmod
=> added r/TNOmod

reddit2telegram/channels/r_pokemonmasters/app.py, reddit2telegram/channels/r_pokemonmasters/tags.txt, reddit2telegram/own.cron
https://www.reddit.com/r/PokemonMasters/
https://t.me/r_PokemonMasters
=> Add r/PokemonMasters subreddit

README.md
maybe this will help new contributors
=> adding tags.txt

reddit2telegram/channels/r_hermitcraft/app.py, reddit2telegram/channels/r_hermitcraft/tags.txt, reddit2telegram/own.cron
[/r/HermitCraft](https://www.reddit.com/r/HermitCraft/)
[@r_HermitCraft](https://t.me/r_hermitcraft)
=> Add r/HermitCraft

reddit2telegram/channels/r_udemyfreebies/app.py, reddit2telegram/channels/r_udemyfreebies/tags.txt, reddit2telegram/own.cron
[r/udemyfreebies](http://reddit.com/r/udemyfreebies)
[@r_udemyfreebies](https://t.me/r_udemyfreebies)
=> udemyfreebies: new channel

reddit2telegram/channels/r_greenandpleasant/__init__.py, reddit2telegram/channels/r_greenandpleasant/app.py, reddit2telegram/channels/r_greenandpleasant/tags.txt
I added the channel GreenAndPleasant, hope I did everything correctly ^^ thanks for writing that bot!
sadly I don't know how cron works or else I would've added it there too
r_greenandpleasant
t.me/r_greenandpleasant or @r_greenandpleasant
- [✔️] Added `channels/%submodule_name%/app.py` file.
- [✔️] Added `channels/%submodule_name%/__init__.py` file.
- [✔️] Added `channels/%submodule_name%/tags.txt` file.
- [✔️] Already have nice channel's profile pic.
- [✔️] Already have mentioned `@r_channels` and `@reddit2telegram` in the description of your channel.
- [✔️] `@reddit2telegram_bot` added as admin to this channel.
=> new channel

reddit2telegram/channels/china_irl_news/__init__.py, reddit2telegram/channels/china_irl_news/app.py, reddit2telegram/channels/china_irl_news/tags.txt
r/China_irl & r/Chinatown_irl
https://t.me/China_irl_News
=> New channel @China_irl_News

reddit2telegram/channels/china_irl_news/app.py
I previously set the bar too low, need to lift it a bit higher to reduce low quality submission.
Sorry for this inconvenience
=> adjust frequency and vote limit for @China_irl_News

reddit2telegram/channels/r_wireguard/TAGS.txt, reddit2telegram/channels/r_wireguard/__init__.py, reddit2telegram/channels/r_wireguard/app.py
https://www.reddit.com/r/wireguard
https://t.me/r_wireguard
=> Wireguard - Reddit

reddit2telegram/channels/r_twinpeaks/__init__.py, reddit2telegram/channels/r_twinpeaks/app.py, reddit2telegram/channels/r_twinpeaks/tags.text
_TwinPeaks & DavidLynch_
_@r_twinpeaks_
=> Twin Peaks and David Lynch subreddit

reddit2telegram/channels/avatarmemes/__init__.py, reddit2telegram/channels/avatarmemes/app.py, reddit2telegram/channels/avatarmemes/tags.txt, reddit2telegram/own.cron
r/avatarmemes
https://t.me/r_avatar_memes
=> Pls Add avatarmemes

reddit2telegram/channels/r_eldenring/__init__.py, reddit2telegram/channels/r_eldenring/app.py, reddit2telegram/channels/r_eldenring/tags.txt
=> Elden Ring reddit added

reddit2telegram/channels/r_mechanicalkeyboards/__init__.py, reddit2telegram/channels/r_mechanicalkeyboards/app.py, reddit2telegram/channels/r_mechanicalkeyboards/tags.txt
https://www.reddit.com/r/MechanicalKeyboards/
https://telegram.me/r_MechanicalKeyboards
=> Add r/MechanicalKeyboards subreddit

reddit2telegram/channels/r_badcode/__init__.py, reddit2telegram/channels/r_badcode/app.py, reddit2telegram/channels/r_badcode/tags.txt, reddit2telegram/own.cron
[r/badcode](https://reddit.com/r/badcode)
[@r_badcode](https://t.me/r_badcode)
=> @r_badcode

reddit2telegram/channels/reddit_elm/__init__.py, reddit2telegram/channels/reddit_elm/app.py, reddit2telegram/channels/reddit_elm/tags.txt, reddit2telegram/own.cron
[r/elm](https://www.reddit.com/r/elm/)
[reddit_elm](https://t.me/reddit_elm)
=> feat: elm reddit channel

reddit2telegram/channels/r_frogs/app.py
Changed some settings because the bot currently doesn't post at all.
/r/frogs
https://t.me/r_frogs
=> Update settings for /r/frogs

reddit2telegram/channels/r_eldenring/app.py
=> updated min_upvotes_limit

reddit2telegram/channels/r_linuxmemes/app.py
All fullfilled
Just was getting duplicate posts
And thought of lowering the min upvote limit
=> r/linuxmemes Set min_upvote_limit to 25 from 50

reddit2telegram/channels/r_askmen/__init__.py, reddit2telegram/channels/r_askmen/app.py, reddit2telegram/channels/r_askmen/tags.txt
[/r/AskMen](https://www.reddit.com/r/askmen/)
[@r_askmen](https://t.me/r_askmen) 
=> Add /r/AskMen

reddit2telegram/channels/r_scala/__init__.py, reddit2telegram/channels/r_scala/app.py, reddit2telegram/channels/r_scala/tags.txt, reddit2telegram/own.cron
=> Add scala subreddit

reddit2telegram/channels/r_china_irl/app.py
Trivial update to enable text submission for @r_China_irl
https://www.reddit.com/r/China_irl/
https://t.me/r_China_irl
=> enable text submission

reddit2telegram/channels/r_furry_irl/app.py
furry_irl
@rfurryirl
We would like to change posts filtering to include videos
=> video=True on r/furry_irl

reddit2telegram/channels/r_discoelysium/__init__.py, reddit2telegram/channels/r_discoelysium/app.py, reddit2telegram/channels/r_discoelysium/tags.txt
=> Added Disco Elysium Subreddit.

reddit2telegram/channels/reddit_argentina/__init__.py, reddit2telegram/channels/reddit_argentina/app.py, reddit2telegram/channels/reddit_argentina/tags.txt, reddit2telegram/own.cron
r/argentina
`@reddit_argentina`
=> Adds r/argentina

reddit2telegram/channels/r_insidemollywood/__init__.py, reddit2telegram/channels/r_insidemollywood/app.py, reddit2telegram/channels/r_insidemollywood/tags.txt, reddit2telegram/own.cron
/r/InsideMollywood
@r_insidemollywood
=> Add insidemollywood
